// Definición del tipo para el array de ciudades
interface Combinacion {
    combinacion: string;
    costo: number;
    Tipo:string;
  }
  
const ciudadesCombinadas: Combinacion[] = [

{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / FUSAGASUGA - CUNDINAMARCA', costo: 923, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / GACHANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / GIRARDOT - CUNDINAMARCA', costo: 923, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / UBATE - CUNDINAMARCA', costo: 1503, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CAJICA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'CHIA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'COTA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'FUNZA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'FUSAGASUGA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 923, Tipo: 'URBANO'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'GIRARDOT - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 923, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'LA CALERA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MADRID - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'MELGAR - TOLIMA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 923, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SIBATE - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOACHA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'SOPO - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TENJO - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 254, Tipo: 'URBANO'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / CAJICA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / CHIA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / COTA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / FACATATIVA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / FUNZA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / LA CALERA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / MADRID - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / MOSQUERA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / SIBATE - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / SOACHA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / SOPO - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / TENJO - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / TOCANCIPA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / ZIPAQUIRA - CUNDINAMARCA', costo: 1076, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / APARTADO - ANTIOQUIA', costo: 2514, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / LA CEJA - ANTIOQUIA', costo: 1083, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / SANTA FE DE ANTIOQUIA - ANTIOQUIA', costo: 1083, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'BELLO - ANTIOQUIA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'BELLO - ANTIOQUIA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'BELLO - ANTIOQUIA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'BELLO - ANTIOQUIA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'BELLO - ANTIOQUIA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'BELLO - ANTIOQUIA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'BELLO - ANTIOQUIA / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'COPACABANA - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'COPACABANA - ANTIOQUIA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'COPACABANA - ANTIOQUIA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'COPACABANA - ANTIOQUIA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'COPACABANA - ANTIOQUIA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'COPACABANA - ANTIOQUIA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'COPACABANA - ANTIOQUIA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'COPACABANA - ANTIOQUIA / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'ENVIGADO - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ENVIGADO - ANTIOQUIA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ENVIGADO - ANTIOQUIA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ENVIGADO - ANTIOQUIA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ENVIGADO - ANTIOQUIA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ENVIGADO - ANTIOQUIA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ENVIGADO - ANTIOQUIA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ENVIGADO - ANTIOQUIA / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'ITAGUI - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ITAGUI - ANTIOQUIA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ITAGUI - ANTIOQUIA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ITAGUI - ANTIOQUIA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ITAGUI - ANTIOQUIA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ITAGUI - ANTIOQUIA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ITAGUI - ANTIOQUIA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'ITAGUI - ANTIOQUIA / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'MEDELLIN - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'MEDELLIN - ANTIOQUIA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'MEDELLIN - ANTIOQUIA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'MEDELLIN - ANTIOQUIA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'MEDELLIN - ANTIOQUIA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'MEDELLIN - ANTIOQUIA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'MEDELLIN - ANTIOQUIA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'MEDELLIN - ANTIOQUIA / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'SABANETA - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'SABANETA - ANTIOQUIA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'SABANETA - ANTIOQUIA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'SABANETA - ANTIOQUIA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'SABANETA - ANTIOQUIA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'SABANETA - ANTIOQUIA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'SABANETA - ANTIOQUIA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'URBANO'},
{combinacion: 'SABANETA - ANTIOQUIA / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'APARTADO - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 2514, Tipo: 'NACIONAL'},
{combinacion: 'LA CEJA - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 1083, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 785, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / BELLO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'RIONEGRO - ANTIOQUIA / COPACABANA - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'RIONEGRO - ANTIOQUIA / ENVIGADO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'RIONEGRO - ANTIOQUIA / ITAGUI - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'RIONEGRO - ANTIOQUIA / LA ESTRELLA - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'RIONEGRO - ANTIOQUIA / MEDELLIN - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'RIONEGRO - ANTIOQUIA / SABANETA - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'RIONEGRO - ANTIOQUIA / RIONEGRO - ANTIOQUIA', costo: 785, Tipo: 'URBANO'},
{combinacion: 'SANTA FE DE ANTIOQUIA - ANTIOQUIA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 1083, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / CUCUTA - NORTE DE SANTANDER', costo: 1001, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / FLORIDABLANCA - SANTANDER', costo: 656, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / PAMPLONA - NORTE DE SANTANDER', costo: 1530, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / GIRON - SANTANDER', costo: 656, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / LOS PATIOS - NORTE DE SANTANDER', costo: 1001, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / PIEDECUESTA - SANTANDER', costo: 656, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / BOGOTA, D.C. - BOGOTA, D.C.', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'URBANO'},
{combinacion: 'BUCARAMANGA - SANTANDER / FLORIDABLANCA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'BUCARAMANGA - SANTANDER / GIRON - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'BUCARAMANGA - SANTANDER / PIEDECUESTA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'CUCUTA - NORTE DE SANTANDER / BOGOTA, D.C. - BOGOTA, D.C.', costo: 1001, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / BOGOTA, D.C. - BOGOTA, D.C.', costo: 656, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / BUCARAMANGA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'FLORIDABLANCA - SANTANDER / FLORIDABLANCA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'FLORIDABLANCA - SANTANDER / GIRON - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'FLORIDABLANCA - SANTANDER / PIEDECUESTA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'PAMPLONA - NORTE DE SANTANDER / BOGOTA, D.C. - BOGOTA, D.C.', costo: 1530, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / BOGOTA, D.C. - BOGOTA, D.C.', costo: 656, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / BUCARAMANGA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'GIRON - SANTANDER / FLORIDABLANCA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'GIRON - SANTANDER / GIRON - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'GIRON - SANTANDER / PIEDECUESTA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'LOS PATIOS - NORTE DE SANTANDER / BOGOTA, D.C. - BOGOTA, D.C.', costo: 1001, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / BOGOTA, D.C. - BOGOTA, D.C.', costo: 656, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / BUCARAMANGA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'PIEDECUESTA - SANTANDER / FLORIDABLANCA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'PIEDECUESTA - SANTANDER / GIRON - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'PIEDECUESTA - SANTANDER / PIEDECUESTA - SANTANDER', costo: 656, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / GUADALAJARA DE BUGA - VALLE DEL CAUCA', costo: 1764, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / TULUA - VALLE DEL CAUCA', costo: 1005, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GUADALAJARA DE BUGA - VALLE DEL CAUCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 1764, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / CALI - VALLE DEL CAUCA', costo: 600, Tipo: 'URBANO'},
{combinacion: 'CALI - VALLE DEL CAUCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'CALI - VALLE DEL CAUCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'CALI - VALLE DEL CAUCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'TULUA - VALLE DEL CAUCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 1005, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / SOLEDAD - ATLANTICO', costo: 876, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / SABANALARGA - ATLANTICO', costo: 876, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / BOGOTA, D.C. - BOGOTA, D.C.', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'URBANO'},
{combinacion: 'BARRANQUILLA - ATLANTICO / SOLEDAD - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'BARRANQUILLA - ATLANTICO / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'URBANO'},
{combinacion: 'BARRANQUILLA - ATLANTICO / SABANALARGA - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'SOLEDAD - ATLANTICO / BOGOTA, D.C. - BOGOTA, D.C.', costo: 876, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / BARRANQUILLA - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'SOLEDAD - ATLANTICO / SOLEDAD - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'SOLEDAD - ATLANTICO / PUERTO COLOMBIA - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'SOLEDAD - ATLANTICO / SABANALARGA - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / BOGOTA, D.C. - BOGOTA, D.C.', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'URBANO'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / SOLEDAD - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'URBANO'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / SABANALARGA - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'SABANALARGA - ATLANTICO / BOGOTA, D.C. - BOGOTA, D.C.', costo: 876, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / BARRANQUILLA - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'SABANALARGA - ATLANTICO / SOLEDAD - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'SABANALARGA - ATLANTICO / PUERTO COLOMBIA - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'SABANALARGA - ATLANTICO / SABANALARGA - ATLANTICO', costo: 876, Tipo: 'URBANO'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / FLANDES - TOLIMA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLANDES - TOLIMA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / MELGAR - TOLIMA', costo: 923, Tipo: 'NACIONAL'},
{combinacion: 'MELGAR - TOLIMA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 923, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / CARTAGENA - BOLIVAR', costo: 899, Tipo: 'NACIONAL'},
{combinacion: 'CARTAGENA - BOLIVAR / BOGOTA, D.C. - BOGOTA, D.C.', costo: 899, Tipo: 'NACIONAL'},
{combinacion: 'BOGOTA, D.C. - BOGOTA, D.C. / SANTA MARTA - MAGDALENA', costo: 899, Tipo: 'NACIONAL'},
{combinacion: 'SANTA MARTA - MAGDALENA / BOGOTA, D.C. - BOGOTA, D.C.', costo: 899, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / BELLO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / COPACABANA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / ENVIGADO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / ITAGUI - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / LA ESTRELLA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / MEDELLIN - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / SABANETA - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / RIONEGRO - ANTIOQUIA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / CAJICA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / CAJICA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / CAJICA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / CAJICA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / CAJICA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / CAJICA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / CAJICA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / CAJICA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / CHIA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / CHIA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / CHIA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / CHIA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / CHIA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / CHIA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / CHIA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / CHIA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / COTA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / COTA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / COTA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / COTA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / COTA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / COTA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / COTA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / COTA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / FACATATIVA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / FACATATIVA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / FACATATIVA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / FACATATIVA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / FACATATIVA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / FACATATIVA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / FACATATIVA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / FACATATIVA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / FUNZA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / FUNZA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / FUNZA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / FUNZA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / FUNZA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / FUNZA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / FUNZA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / FUNZA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / GACHANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / GACHANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / GACHANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / GACHANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / GACHANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / GACHANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / GACHANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / GACHANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / LA CALERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / LA CALERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / LA CALERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / LA CALERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / LA CALERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / LA CALERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / LA CALERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / LA CALERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / MADRID - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / MADRID - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / MADRID - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / MADRID - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / MADRID - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / MADRID - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / MADRID - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / MADRID - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / MOSQUERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / MOSQUERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / MOSQUERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / MOSQUERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / MOSQUERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / MOSQUERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / MOSQUERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / MOSQUERA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / SIBATE - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / SIBATE - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / SIBATE - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / SIBATE - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / SIBATE - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / SIBATE - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / SIBATE - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / SIBATE - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / SOACHA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / SOACHA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / SOACHA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / SOACHA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / SOACHA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / SOACHA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / SOACHA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / SOACHA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / SOPO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / SOPO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / SOPO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / SOPO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / SOPO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / SOPO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / SOPO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / SOPO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / TENJO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / TENJO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / TENJO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / TENJO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / TENJO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / TENJO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / TENJO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / TENJO - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / TOCANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / TOCANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / TOCANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / TOCANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / TOCANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / TOCANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / TOCANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / TOCANCIPA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'BELLO - ANTIOQUIA / ZIPAQUIRA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'COPACABANA - ANTIOQUIA / ZIPAQUIRA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ENVIGADO - ANTIOQUIA / ZIPAQUIRA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'ITAGUI - ANTIOQUIA / ZIPAQUIRA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'LA ESTRELLA - ANTIOQUIA / ZIPAQUIRA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'MEDELLIN - ANTIOQUIA / ZIPAQUIRA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'SABANETA - ANTIOQUIA / ZIPAQUIRA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'RIONEGRO - ANTIOQUIA / ZIPAQUIRA - CUNDINAMARCA', costo: 624, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / BARRANQUILLA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / SOLEDAD - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / PUERTO COLOMBIA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / SABANALARGA - ATLANTICO', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / CAJICA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / CAJICA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / CAJICA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / CAJICA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / CHIA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / CHIA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / CHIA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / CHIA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / COTA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / COTA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / COTA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / COTA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / FACATATIVA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / FACATATIVA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / FACATATIVA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / FACATATIVA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / FUNZA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / FUNZA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / FUNZA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / FUNZA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / GACHANCIPA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / GACHANCIPA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / GACHANCIPA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / GACHANCIPA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / LA CALERA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / LA CALERA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / LA CALERA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / LA CALERA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / MADRID - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / MADRID - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / MADRID - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / MADRID - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / MOSQUERA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / MOSQUERA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / MOSQUERA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / MOSQUERA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / SIBATE - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / SIBATE - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / SIBATE - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / SIBATE - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / SOACHA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / SOACHA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / SOACHA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / SOACHA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / SOPO - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / SOPO - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / SOPO - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / SOPO - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / TENJO - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / TENJO - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / TENJO - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / TENJO - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / TOCANCIPA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / TOCANCIPA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / TOCANCIPA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / TOCANCIPA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'BARRANQUILLA - ATLANTICO / ZIPAQUIRA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SOLEDAD - ATLANTICO / ZIPAQUIRA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'PUERTO COLOMBIA - ATLANTICO / ZIPAQUIRA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'SABANALARGA - ATLANTICO / ZIPAQUIRA - CUNDINAMARCA', costo: 828, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / BUCARAMANGA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / FLORIDABLANCA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / GIRON - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / PIEDECUESTA - SANTANDER', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / COTA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / COTA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / COTA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / COTA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / GACHANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / GACHANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / GACHANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / GACHANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'BUCARAMANGA - SANTANDER / ZIPAQUIRA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FLORIDABLANCA - SANTANDER / ZIPAQUIRA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GIRON - SANTANDER / ZIPAQUIRA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PIEDECUESTA - SANTANDER / ZIPAQUIRA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CAJICA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CHIA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'COTA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FACATATIVA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'FUNZA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'GACHANCIPA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'LA CALERA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MADRID - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'MOSQUERA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SIBATE - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOACHA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'SOPO - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TENJO - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'TOCANCIPA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / CALI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / PALMIRA - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / JAMUNDI - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'ZIPAQUIRA - CUNDINAMARCA / YUMBO - VALLE DEL CAUCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / CAJICA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / CHIA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / COTA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / COTA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / COTA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / COTA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / FACATATIVA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / FUNZA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / GACHANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / GACHANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / GACHANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / GACHANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / LA CALERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / MADRID - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / MOSQUERA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / SIBATE - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / SOACHA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / SOPO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / TENJO - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / TOCANCIPA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'CALI - VALLE DEL CAUCA / ZIPAQUIRA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'PALMIRA - VALLE DEL CAUCA / ZIPAQUIRA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'JAMUNDI - VALLE DEL CAUCA / ZIPAQUIRA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'},
{combinacion: 'YUMBO - VALLE DEL CAUCA / ZIPAQUIRA - CUNDINAMARCA', costo: 642, Tipo: 'NACIONAL'}
  ];
  
  export { ciudadesCombinadas};