// Definición del tipo para el array de ciudades
interface Ciudad {
  nombre: string;
  costo: number;
}

const ciudades: Ciudad[] = [
  {nombre:'AGUA DE DIOS - CUNDINAMARCA', costo:85},
  {nombre:'AGUACHICA - CESAR', costo:67},
  {nombre:'ANDALUCIA - VALLE DEL CAUCA', costo:114},
  {nombre:'APARTADO - ANTIOQUIA', costo:74},
  {nombre:'ARAUCA - ARAUCA', costo:68},
  {nombre:'ARMENIA - ANTIOQUIA', costo:116},
  {nombre:'ARMENIA - QUINDIO', costo:34},
  {nombre:'BARBOSA - ANTIOQUIA', costo:118},
  {nombre:'BARBOSA - SANTANDER', costo:100},
  {nombre:'BARRANCABERMEJA - SANTANDER', costo:48},
  {nombre:'BARRANQUILLA - ATLANTICO', costo:35},
  {nombre:'BELLO - ANTIOQUIA', costo:12},
  {nombre:'BOGOTA, D.C. - BOGOTA, D.C.', costo:33},
  {nombre:'BOYACA - BOYACA', costo:91},
  {nombre:'BUCARAMANGA - SANTANDER', costo:22},
  {nombre:'BUENAVENTURA - VALLE DEL CAUCA', costo:46},
  {nombre:'CAICEDONIA - VALLE DEL CAUCA', costo:84},
  {nombre:'CAJAMARCA - TOLIMA', costo:93},
  {nombre:'CALARCA - QUINDIO', costo:60},
  {nombre:'CALI - VALLE DEL CAUCA', costo:4},
  {nombre:'CARTAGENA - BOLIVAR', costo:40},
  {nombre:'CARTAGO - VALLE DEL CAUCA', costo:37},
  {nombre:'CAUCASIA - ANTIOQUIA', costo:73},
  {nombre:'CERETE - CORDOBA', costo:106},
  {nombre:'CHAPARRAL - TOLIMA', costo:61},
  {nombre:'CHIA - CUNDINAMARCA', costo:109},
  {nombre:'CHIGORODO - ANTIOQUIA', costo:122},
  {nombre:'CHINCHINA - CALDAS', costo:44},
  {nombre:'CHIQUINQUIRA - BOYACA', costo:39},
  {nombre:'CIENAGA - MAGDALENA', costo:54},
  {nombre:'CIRCASIA - QUINDIO', costo:115},
  {nombre:'COPACABANA - ANTIOQUIA', costo:3},
  {nombre:'COROZAL - SUCRE', costo:88},
  {nombre:'COTA - CUNDINAMARCA', costo:15},
  {nombre:'CUCUTA - NORTE DE SANTANDER', costo:49},
  {nombre:'DOSQUEBRADAS - RISARALDA', costo:21},
  {nombre:'DUITAMA - BOYACA', costo:26},
  {nombre:'EL CARMEN DE BOLIVAR - BOLIVAR', costo:125},
  {nombre:'ENVIGADO - ANTIOQUIA', costo:9},
  {nombre:'ESPINAL - TOLIMA', costo:27},
  {nombre:'FACATATIVA - CUNDINAMARCA', costo:53},
  {nombre:'FLORENCIA - CAQUETA', costo:63},
  {nombre:'FLORIDABLANCA - SANTANDER', costo:23},
  {nombre:'FRESNO - TOLIMA', costo:99},
  {nombre:'FUNDACION - MAGDALENA', costo:75},
  {nombre:'FUNZA - CUNDINAMARCA', costo:7},
  {nombre:'FUSAGASUGA - CUNDINAMARCA', costo:38},
  {nombre:'GARZON - HUILA', costo:81},
  {nombre:'GIRARDOT - CUNDINAMARCA', costo:17},
  {nombre:'GIRON - SANTANDER', costo:20},
  {nombre:'GUADALAJARA DE BUGA - VALLE DEL CAUCA', costo:123},
  {nombre:'HONDA - TOLIMA', costo:43},
  {nombre:'IBAGUE - TOLIMA', costo:18},
  {nombre:'IPIALES - NARIÑO', costo:78},
  {nombre:'ITAGUI - ANTIOQUIA', costo:13},
  {nombre:'JAMUNDI - VALLE DEL CAUCA', costo:5},
  {nombre:'LA CEJA - ANTIOQUIA', costo:31},
  {nombre:'LA DORADA - CALDAS', costo:55},
  {nombre:'LA ESTRELLA - ANTIOQUIA', costo:11},
  {nombre:'LA PLATA - HUILA', costo:86},
  {nombre:'LA VEGA - CAUCA', costo:117},
  {nombre:'LIBANO - TOLIMA', costo:90},
  {nombre:'LORICA - CORDOBA', costo:76},
  {nombre:'LOS PATIOS - NORTE DE SANTANDER', costo:103},
  {nombre:'MAGANGUE - BOLIVAR', costo:77},
  {nombre:'MAICAO - LA GUAJIRA', costo:70},
  {nombre:'MANIZALES - CALDAS', costo:30},
  {nombre:'MARIQUITA - TOLIMA', costo:98},
  {nombre:'MEDELLIN - ANTIOQUIA', costo:10},
  {nombre:'MOCOA - PUTUMAYO', costo:82},
  {nombre:'MONIQUIRA - BOYACA', costo:97},
  {nombre:'MONTELIBANO - CORDOBA', costo:107},
  {nombre:'MONTERIA - CORDOBA', costo:58},
  {nombre:'MOSQUERA - CUNDINAMARCA', costo:110},
  {nombre:'NEIVA - HUILA', costo:25},
  {nombre:'OCAÑA - NORTE DE SANTANDER', costo:69},
  {nombre:'OICATA - BOYACA', costo:94},
  {nombre:'PAIPA - BOYACA', costo:42},
  {nombre:'PALMIRA - VALLE DEL CAUCA', costo:16},
  {nombre:'PAMPLONA - NORTE DE SANTANDER', costo:62},
  {nombre:'PASTO - NARIÑO', costo:50},
  {nombre:'PEREIRA - RISARALDA', costo:19},
  {nombre:'PIEDECUESTA - SANTANDER', costo:24},
  {nombre:'PITAL - HUILA', costo:47},
  {nombre:'PITALITO - HUILA', costo:65},
  {nombre:'POPAYAN - CAUCA', costo:45},
  {nombre:'PUERTO ASIS - PUTUMAYO', costo:80},
  {nombre:'PUERTO COLOMBIA - ATLANTICO', costo:121},
  {nombre:'PUERTO TEJADA - CAUCA', costo:124},
  {nombre:'QUIBDO - CHOCO', costo:119},
  {nombre:'QUIMBAYA - QUINDIO', costo:102},
  {nombre:'RIOHACHA - LA GUAJIRA', costo:64},
  {nombre:'RIONEGRO - ANTIOQUIA', costo:32},
  {nombre:'RIOSUCIO - CALDAS', costo:101},
  {nombre:'SABANALARGA - ANTIOQUIA', costo:113},
  {nombre:'SABANALARGA - ATLANTICO', costo:104},
  {nombre:'SABANETA - ANTIOQUIA', costo:14},
  {nombre:'SAHAGUN - CORDOBA', costo:120},
  {nombre:'SALGAR - ANTIOQUIA', costo:96},
  {nombre:'SAN AGUSTIN - HUILA', costo:108},
  {nombre:'SAN ALBERTO - CESAR', costo:83},
  {nombre:'SAN GIL - SANTANDER', costo:56},
  {nombre:'SAN JOSE DEL GUAVIARE - GUAVIARE', costo:79},
  {nombre:'SAN JUAN DEL CESAR - LA GUAJIRA', costo:87},
  {nombre:'SANTA FE DE ANTIOQUIA - ANTIOQUIA', costo:92},
  {nombre:'SANTA MARTA - MAGDALENA', costo:41},
  {nombre:'SARAVENA - ARAUCA', costo:89},
  {nombre:'SINCELEJO - SUCRE', costo:72},
  {nombre:'SOACHA - CUNDINAMARCA', costo:112},
  {nombre:'SOCORRO - SANTANDER', costo:66},
  {nombre:'SOGAMOSO - BOYACA', costo:29},
  {nombre:'SOLEDAD - ATLANTICO', costo:36},
  {nombre:'TENJO - CUNDINAMARCA', costo:111},
  {nombre:'TULUA - VALLE DEL CAUCA', costo:51},
  {nombre:'TUMACO - NARIÑO', costo:95},
  {nombre:'TUNJA - BOYACA', costo:8},
  {nombre:'UBATE - CUNDINAMARCA', costo:59},
  {nombre:'VALLEDUPAR - CESAR', costo:57},
  {nombre:'VILLAMARIA - CALDAS', costo:28},
  {nombre:'VILLAVICENCIO - META', costo:2},
  {nombre:'YARUMAL - ANTIOQUIA', costo:105},
  {nombre:'YOPAL - CASANARE', costo:71},
  {nombre:'YUMBO - VALLE DEL CAUCA', costo:6},
  {nombre:'ZIPAQUIRA - CUNDINAMARCA', costo:52}
  
];

export { ciudades};